### ISSUE TITLE
UTF-8 when export

### ISSUE THREAD

**Issue by tabooo** [yugandhargangu/JspMyAdmin2#11]
there are '?????'  characters when exporting utf-8 database. I fix it:
In ExportLogic.Class
change line 106: outputStreamWriter = new OutputStreamWriter(fileOutputStream);
to: outputStreamWriter = new OutputStreamWriter(fileOutputStream, "UTF-8");

**Comment by yugandhargangu** [comment]
Fixed in JspMyAdminV1.0.3
