### ISSUE TITLE
MySQL connection problem when not installed locally

### ISSUE THREAD

**Issue by youyizhongzhuangtaijiaofangkong** [yugandhargangu/JspMyAdmin2#14]
How can find the Database file ?

**Comment by yugandhargangu** [comment]
I didn't get what is your issue??
Could you please post more details about the issue?

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
I means !I didn't find the configuration settings.It can start without a database?

**Comment by yugandhargangu** [comment]
Yes. You just have to put war file in your webapps then run it on browser.
It will automatically redirect to configuration page. There you can set server configuration.

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
I see !Think you !I want the same time Manage several databases!So I need to make some changes

**Comment by yugandhargangu** [comment]
You can select half configuration item in configuration page So you can change database every time.

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
OK!I will have a try!

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
If I did not install the database locally. I will trun to uninstall.html，Is this can only manage local databases?

**Comment by shashankitmaster** [comment]
@shuaiqixiaoyumi :  How are you connecting your mysql if it is not installed locally? 
Can you share the way of your configuration?

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
locally means database is not on my computer


发自网易邮箱 iPhone 版
在2017年08月04日 12:06，Shashank Acharya 写道:

@shuaiqixiaoyumi : How are you connecting your mysql if it is not installed locally?
Can you share the way of your configuration?

**Comment by shashankitmaster** [comment]
@shuaiqixiaoyumi I know that locally means database not on my computer. 

Currently when you install you are adding some path for MySQL, I want to know how are doing configuration at time of installation. Are you getting some errors or anything you share then we can reproduce the same scenario at our side.

If you can't then I need to remove the issue.

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
I was running in eclipse By maven build tomcat7:run， and start succed then do noting.
When I visit this address about 'http://localhost:8010/' and do nothing else,
It turns to 'http://localhost:8010/uninstall.html' .

**Comment by youyizhongzhuangtaijiaofangkong** [comment]
I means Why he accessed login.html directly to home.html then to uninstall.html
