### ISSUE TITLE
issue when serving via https

### ISSUE THREAD

**Issue by sal2row** [yugandhargangu/JspMyAdmin2#21]
Hey Yugandhar,
kudos for your tool! I've used it successfully on a tomcat 7 via http,
moreover I also need to use it via a tomcat 7 which is served through https:
in the latter case I've never been able to get the starting configuration page loaded in my browser:

the url "https://host:8443/jspmyadmin/" is redirected to "https://jspmyadmin/login.html"

- which of course doesn't exist. correspondingly, in the tomcat access log I see lines such as:
""GET //jspmyadmin/ HTTP/1.1" 302  //jspmyadmin/"

I didn't quite look extensively into your code, however may you please provide some advice
in case there's any config tweak I'm missing?
if on the other hand this requires new developments, are you planning to get this handled?

thanks in advance
Sal

**Comment by yugandhargangu** [comment]
Fixed in Version 1.0.5
