### ISSUE TITLE
utf-8 characters

### ISSUE THREAD

**Issue by tabooo** [yugandhargangu/JspMyAdmin2#3]
can not insert utf-8 characters. '???????' inserted

**Comment by yugandhargangu** [comment]
Can you add more information that on which screen it is giving error.

**Comment by yugandhargangu** [comment]
Bug Fixed

**Comment by tabooo** [comment]
in ApiConnectionImpl class I added this line after "builder.append(_YEARISDATETYPE);" lines and it works now.
builder.append("&useUnicode=true&characterEncoding=UTF-8");

**Comment by yugandhargangu** [comment]
It was fixed in next version.
This also good solution for utf-8 characters but won't work for remaining encodings.

**Comment by yugandhargangu** [comment]
Thank you so much for reporting. So I could able to fix it. :)
